<?php

/**
 * @file
 * Hook implementations for Boston College.
 */

define('BOSTON_COLLEGE_ARCHIVAL_PDF_DATASTREAM_ID', 'ARCHIVE-PDF');
define('BOSTON_COLLEGE_VIDEO_CONTENT_MODEL', 'islandora:BCVideo');
define('BOSTON_COLLEGE_VIDEO_FORM', 'BC Video MODS Form');
define('BOSTON_COLLEGE_GRADUATE_THESIS_CONTENT_MODEL', 'ir:graduateETDCModel');
define('BOSTON_COLLEGE_UNDERGRADUATE_THESIS_CONTENT_MODEL', 'ir:undergraduateETDCModel');

/**
 * Implements hook_menu_alter().
 */
function boston_college_menu_alter(&$items) {
  // Swap in our alternate form.
  $items['islandora/object/%islandora_object/islandora_scholar_upload'] = array(
    'file path' => drupal_get_path('module', 'boston_college'),
    'file' => 'includes/document.tab.inc',
    'page callback' => 'boston_college_document_view',
  ) + $items['islandora/object/%islandora_object/islandora_scholar_upload'];
}

/**
 * Implements hook_islandora_ingest_steps_alter().
 */
function boston_college_islandora_ingest_steps_alter(&$steps, &$form_state) {
  unset($steps['islandora_scholar_file_upload']);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function boston_college_islandora_ingest_steps(array $form_state) {
  $models = boston_college_citation_models();

  $steps = array();
  $shared_storage = islandora_ingest_form_get_shared_storage($form_state);

  if (array_intersect($models, $shared_storage['models'])) {
    $steps['boston_college_document_upload'] = array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'boston_college_document_upload_ingest_step_form',
      'module' => 'boston_college',
      'file' => 'includes/document.ingest_step.inc',
    );
  }

  return $steps;
}

/**
 * Alter the image_field_caption field to look like it takes a URL.
 */
function boston_college_field_widget_form_alter(&$element, &$form_state, $context) {
  // Add display_field setting to field because file_field_widget_form() assumes
  // it is set.
  $instance = $context['instance'];
  $settings = $instance['settings'];

  if (isset($settings['image_field_caption']) && $instance['widget']['type'] == 'image_image' && $settings['image_field_caption']) {
    foreach (element_children($element) as $delta) {
      // Add all extra functionality provided by the image widget.
      $element[$delta]['#process'][] = 'boston_college_image_field_caption_widget_process';
    }
  }
}

/**
 * An element #process callback for the image_image field type.
 *
 * Expands the image_image type to include the alt and title fields.
 */
function boston_college_image_field_caption_widget_process($element, &$form_state, $form) {
  // Add the additional alt and title fields.
  $element['image_field_caption']['#title'] = t('Link');
  $element['image_field_caption']['#base_type'] = 'textfield';
  $element['image_field_caption']['#format'] = 'plain_text';
  $element['image_field_caption']['#description'] = t('The link the image will redirect to.');
  return $element;
}

/**
 * Implements hook_islandora_derivative().
 */
function boston_college_islandora_derivative(AbstractObject $object = NULL) {
  $mod_path = drupal_get_path('module', 'boston_college');
  $derivatives = array(
    array(
      'source_dsid' => 'MODS',
      'destination_dsid' => NULL,
      'weight' => 0,
      'function' => array(
        'boston_college_update_object_label_from_mods_derivative',
      ),
      'file' => "$mod_path/includes/derivatives.inc",
    ),
  );

  $models = boston_college_citation_models();
  if (array_intersect($models, $object->models)) {
    $derivatives[] = array(
      'source_dsid' => BOSTON_COLLEGE_ARCHIVAL_PDF_DATASTREAM_ID,
      'destination_dsid' => 'PDF',
      'function' => array(
        'boston_college_build_pdf',
      ),
      'file' => "$mod_path/includes/splash.inc",
    );
  }

  return $derivatives;
}

/**
 * Grab models used to represent citations.
 *
 * @return array
 *   An array of strings representing content model PIDs.
 */
function boston_college_citation_models() {
  return array(
    'ir:citationCModel',
    'ir:thesisCModel',
  );
}

/**
 * Implements hook_islandora_datastream_purged().
 */
function boston_college_islandora_datastream_purged(AbstractObject $object, $dsid) {
  $models = boston_college_citation_models();
  $purge_derived_dsids = array(
    BOSTON_COLLEGE_ARCHIVAL_PDF_DATASTREAM_ID,
    'PDF',
  );

  if (!(in_array($dsid, $purge_derived_dsids) && array_intersect($models, $object->models))) {
    return;
  }

  module_load_include('inc', 'islandora', 'includes/utilities');
  $hooks = islandora_invoke_hook_list(ISLANDORA_DERVIATIVE_CREATION_HOOK, $object->models, array($object));

  $hook_filter = function ($hook_def) use ($purge_derived_dsids) {
    return isset($hook_def['source_dsid']) && isset($hook_def['destination_dsid']) ?
      in_array($hook_def['source_dsid'], $purge_derived_dsids) :
      FALSE;
  };
  $hooks = array_filter($hooks, $hook_filter);

  $dsid_map = function ($hook_definition) {
    return $hook_definition['destination_dsid'];
  };

  $dsids = array_map($dsid_map, $hooks);
  array_map(array($object, 'purgeDatastream'), $dsids);
}

/**
 * Implements hook_menu().
 */
function boston_college_menu() {
  $items = array();

  $items['admin/islandora/boston_college'] = array(
    'title' => 'Boston College Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('boston_college_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );

  return $items;
}

/**
 * Implements islandora_required_objects().
 */
function boston_college_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'boston_college');
  $islandora_path = drupal_get_path('module', 'islandora');

  // Video Content Model.
  $video_content_model = $connection->repository->constructObject(BOSTON_COLLEGE_VIDEO_CONTENT_MODEL);
  $video_content_model->owner = 'fedoraAdmin';
  $video_content_model->label = 'Boston College Video Content Model';
  $video_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $video_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/boston_college_video_ds_composite.xml", FALSE);
  $video_content_model->ingestDatastream($datastream);

  // Graduate Thesis Content Model.
  $graduate_thesis_content_model = $connection->repository->constructObject(BOSTON_COLLEGE_GRADUATE_THESIS_CONTENT_MODEL);
  $graduate_thesis_content_model->owner = 'fedoraAdmin';
  $graduate_thesis_content_model->label = 'BC Graduate Thesis Content Model';
  $graduate_thesis_content_model->models = 'fedora-system:ContentModel-3.0';

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $graduate_thesis_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/boston_college_graduate_thesis_ds_composite.xml", FALSE);
  $graduate_thesis_content_model->ingestDatastream($datastream);

  // Graduate Theses Collection.
  $graduate_collection = $connection->repository->constructObject('ir:GraduateThesesCollection');
  $graduate_collection->owner = 'fedoraAdmin';
  $graduate_collection->label = 'Graduate ETDs';
  $graduate_collection->models = 'islandora:collectionCModel';
  $graduate_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:bc-root');

  // Collection Policy Datastream.
  $datastream = $graduate_collection->constructDatastream('COLLECTION_POLICY', 'M');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/boston_college_graduate_thesis_collection_policy.xml", FALSE);
  $graduate_collection->ingestDatastream($datastream);

  // TN Datastream.
  $datastream = $graduate_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $graduate_collection->ingestDatastream($datastream);

  // Undergraduate Thesis Content Model.
  $undergraduate_thesis_content_model = $connection->repository->constructObject(BOSTON_COLLEGE_UNDERGRADUATE_THESIS_CONTENT_MODEL);
  $undergraduate_thesis_content_model->owner = 'fedoraAdmin';
  $undergraduate_thesis_content_model->label = 'BC Undergraduate Honors Thesis Content Model';
  $undergraduate_thesis_content_model->models = 'fedora-system:ContentModel-3.0';

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $undergraduate_thesis_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/boston_college_undergraduate_thesis_ds_composite.xml", FALSE);
  $undergraduate_thesis_content_model->ingestDatastream($datastream);

  // Undergraduate Honors Theses Collection.
  $undergraduate_collection = $connection->repository->constructObject('ir:honorsThesesCollection');
  $undergraduate_collection->owner = 'fedoraAdmin';
  $undergraduate_collection->label = 'Undergraduate Honors Theses';
  $undergraduate_collection->models = 'islandora:collectionCModel';
  $undergraduate_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:bc-root');

  // Collection Policy Datastream.
  $datastream = $undergraduate_collection->constructDatastream('COLLECTION_POLICY', 'M');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/boston_college_graduate_thesis_collection_policy.xml", FALSE);
  $undergraduate_collection->ingestDatastream($datastream);

  // TN Datastream.
  $datastream = $undergraduate_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $undergraduate_collection->ingestDatastream($datastream);

  return array(
    'boston_college' => array(
      'title' => 'Boston College',
      'objects' => array(
        $video_content_model,
        $graduate_thesis_content_model,
        $graduate_collection,
        $undergraduate_thesis_content_model,
        $undergraduate_collection,
      ),
    ),
  );
}

/**
 * Implements islandora_xml_form_builder_forms().
 */
function boston_college_islandora_xml_form_builder_forms() {
  return array(
    BOSTON_COLLEGE_VIDEO_FORM => array(
      'form_file' => drupal_get_path('module', 'boston_college') . '/xml/bc_video_mods_form.xml',
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function boston_college_islandora_xml_form_builder_form_associations() {
  return array(
    'boston_college_video_mods_form' => array(
      'content_model' => BOSTON_COLLEGE_VIDEO_CONTENT_MODEL,
      'form_name' => BOSTON_COLLEGE_VIDEO_FORM,
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_ingest_steps().
 */
function boston_college_islandora_BCVideo_islandora_ingest_steps() {
  return array(
    'boston_college_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'boston_college_video_upload_form',
      'module' => 'boston_college',
      'file' => 'includes/video_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_derivative().
 */
function boston_college_islandora_BCVideo_islandora_derivative() {
  return array(
    array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'TN',
      'weight' => '0',
      'function' => array(
        'islandora_video_create_thumbnail',
      ),
      'file' => drupal_get_path('module', 'islandora_video') . '/includes/derivatives.inc',
    ),
    array(
      'source_dsid' => 'MODS',
      'destination_dsid' => 'STREAM',
      'weight' => '0',
      'function' => array(
        'boston_college_create_stream',
      ),
      'file' => drupal_get_path('module', 'boston_college') . '/includes/derivatives.inc',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function boston_college_theme($existing, $type, $theme, $path) {
  return array(
    'boston_college_video' => array(
      'variables' => array('object' => NULL),
      'file' => 'theme/theme.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function boston_college_islandora_BCVideo_islandora_view_object(AbstractObject $object) {
  return array(theme('boston_college_video', array('object' => $object)));
}
